name:                brnfck
version:             0.1.0.0
github:              "KacperFKorban/brnfck"
license:             BSD3
author:              "Kacper Korban"
maintainer:          "kacper.f.korban@gmail.com"
copyright:           "Copyright: (c) 2020 Kacper Korban"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KacperFKorban/brnfck#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- lens

library:
  source-dirs: src

executables:
  brnfck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brnfck

tests:
  brnfck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brnfck
